Created personal portfolio with html and css.
claudiapao10/software-product-sprint pull request #1
Opened 2021-02-25 18:28 UTC by claudiapao10

I created 6 html files and one css file:
* Home
* Gallery
* SPS
* About me
* Contact
* Projects

2021-02-25 20:36 UTC, GoogleyGabriel requested changes
Looking great! Good job :) Made a few comments that should aid in readability and reusability of the code. Ready to approve after they've been addressed.

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/about-me.html
> +                computer science
These line breaks look odd. Try to format using `<br>`. This is a nice resource: https://www.w3schools.com/tags/tag_br.asp

Sprinkle some line breaks throughout this paragraph. Smaller chunks are easier to read.

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/about-me.html
> +                student. I originated in the town of Humacao, Puerto Rico and continued my studies in Bayamón, where I
Try adding a hyperlink for practice :) For example, link "Humcao, Puerto Rico" to https://www.google.com/maps/place/Humacao,+Puerto+Rico/@22.620792,-56.4098252,3.09z/data=!4m5!3m4!1s0x8c04a898d87093e3:0xceb5e85b1704d482!8m2!3d18.1551337!4d-65.8203943.

A hyperlink is [this](https://www.google.com/maps/place/Humacao,+Puerto+Rico/@22.620792,-56.4098252,3.09z/data=!4m5!3m4!1s0x8c04a898d87093e3:0xceb5e85b1704d482!8m2!3d18.1551337!4d-65.8203943)

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/about-me.html
> +            <br>
Look into adding padding instead of using <br>. 
https://www.htmldog.com/guides/css/beginner/margins/
https://www.w3schools.com/cssref/pr_padding.asp

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/about-me.html
> +                together were key to deciding on the career that I am currently in.</p>
Use `<br>` for line breaks.

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/about-me.html
> +                 an initiative or be part of one as this would give girls and women opportunities in the field beforehand.</p>
Line breaks aid in readability, please add some linebreaks.

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/gallery.html
> +            <img src="images/family.jpg" alt="">
Please add alt text, it helps with accessibility for those that may have issues reading .

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/index.html
> +
remove unnecessary extra lines. Only add extra lines when it aids in readability.

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/index.html
> +                    <h1>&lt Greeting &GT</h1>
Thats cool!

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/projects.html
> +                <li><a href="contact.html">Contact</a></li>
You are going to be copy-pasting this a lot. You can automate a lot of things like this. Take a look at this: https://stackoverflow.com/a/42333464

2021-02-25 20:36 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/sps.html
> +
Look into padding.

2021-02-28 18:35 UTC, GoogleyGabriel approved these changes
Looking great! Just make sure you format your file correctly (it aids a lot in readability). Everything else looks perfect!

2021-02-28 18:35 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/about-me.html
> +                the near future I can positively impact the community. <br>
There seem to be some odd line breaks in some of your paragraphs. For example, why is there a line break between 
"so that in" and "the near future I can positively impact the community."? I think this could all be in the same line.

2021-02-28 18:35 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/about-me.html
> +                 Having the opportunity to meet a large number of people who spoke so passionately about their projects or their work and the great experience that I had
Try to keep the length of chars <= 80. I think the IDE you are using should have an auto format, and it should also allow you to install extensions that should do the formatting for you :)

2021-02-28 18:35 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/about-me.html
> +                 part of the Puerto Rican economy falls on small and local businesses. On top of that, one of my goals is to be part of the
Same as above.

2021-02-28 18:35 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/index.html
> +
No need for this new line.

2021-02-28 18:35 UTC, GoogleyGabriel commented on portfolio/src/main/webapp/style.css
> +    padding-top: 20px; /**ADDED: to replace the <br> in the html file*/
Nit: In general, you don't need to explain your styling with comments in .css files unless you are doing something super tricky.

2021-03-02 03:20 UTC, sebagabs commented on portfolio/src/main/webapp/style.css
> +                                                            /**GALLERY.HTML*/
Nit: I know Gabriel already commented about commenting `.css` files, and I don't know if it's me or GitHub, but some comments you made appear to be "centered" for some reason. I think it's better if it's just at the beginning like the rest of the lines.

```suggestion
 /**GALLERY.HTML*/
```

2021-03-02 03:25 UTC, sebagabs approved these changes
I'm not an expert at **html**, **css** and **js**, but all these lines are looking good. Seems like a good page, keep up the work!

2021-03-02 19:54 UTC, claudiapao10 commented on portfolio/src/main/webapp/style.css
> +                                                            /**GALLERY.HTML*/
Thanks for the feedback Sebastian! I changed the comments in the style.css based on both suggestions.

2021-03-03 13:32 UTC, merged